### PR TITLE
Auth modal

### PR DESCRIPTION
**Pull request by redconOne**
# **schema.prisma** 
### Location Table 
- Added zipCode 
- Added locationName ( will be stored as "city, state")  
# **_container.tsx** 
### LOGIN Button 
- Only shows when session is not available
- Utilizes allowed providers from auth
### LOGOUT Button
- Only shows when session is available 
- Once clicked logs user out, but maintains current url 
# **index.tsx** 
### Auth Showcase 
- Removed Auth Showcase Example entirely
# **root.ts**
- Added authRouter
# **auth.ts**
### editUser
- Added protectedProcedure router for mutating user first and last name
- Meant to be utilized during the onboarding process in onboarding.tsx

### CODE REVIEW

**Comment by burhan-syed** [comment]
Leaving this note here as to why the Vercel build is failing: 

> Build optimization failed: found page without a React Component as default export in 
pages/auth/signup
See https://nextjs.org/docs/messages/page-without-valid-component for more info.

**Comment by redconOne** [comment]
@burhan-syed I removed the signup.tsx, but it looks like it's still failing Vercel. I don't have permissions on Vercel to see why it's failing now though.

**Review by tgharbert — APPROVED** [review]
Thanks for updating the schema and zip code ideas. Everything looks good!

**Review by tgharbert — APPROVED** [review]
Thanks!

**Pull request merged**
